### ISSUE TITLE
About exit probability

### ISSUE THREAD

**Issue by luzai** [mileyan/DARENet#9]
Hi, mileyan. Thank you very much for your inspiring work! 
May I ask why you calculate the exit probability $q_s$ by 
![image](https://user-images.githubusercontent.com/14788650/64516996-09e71a00-d322-11e9-82a9-1a2fb185b7b5.png)
, rather than  
![image](https://user-images.githubusercontent.com/14788650/64517103-3d29a900-d322-11e9-8122-bc7a12850e92.png)

**Comment by YurongYou** [comment]
Hi Luzai,

The q_s here is the probability that the example will exit from stage s, conditioned on that the example does not exit from previous stages. Thus q_s = P(exit from stage s | not exist from previous stages) = P(exit from stage s & not exist from previous stages) / P(not exist from previous stages) = P(exit from stage s) / P(not exist from previous stages) = p_s / (1 - sum(p1, p2, ..., p_{s-1})).

**Comment by luzai** [comment]
Hi Yurong, 

Thanks a lot for your detailed explanation! I understand that q_s = P(exit from stage s | not exist from previous stages) and p_s=P(exit from stage s & not exist from previous stages).
